### PR TITLE
Features/gh 84 openstack anti affinity policy

### PR DESCRIPTION
**Pull request by stebenoist**
See https://github.com/ystia/yorc/pull/356

### CODE REVIEW

**Comment by laurentganne** [comment]
A topology template creator who defines a portable application, might want to associate his compute nodes to an anti-affinity placement policy, to clearly describe his intention regarding the expected deployment.
So he may choose to use the abstract policy component `AntiAffinity` in his topology template to make sure this abstract component will be matched against an AntiAffinity policy and not an Affinity policy.

If the topology template creator has to associate his template to the abstract parent `Placement` policy,
then nothing would prevent a user of this template to deploy the topology on a location having only an Affinity placement policy,
without realizing he will run a deployment implementing the contrary of what the designer of the topology had in mind.

Maybe it would be better to have different concrete types: `OpenStackAffinity` policy, `OpenStackAntiAffinity` policy, etc... inheriting from abstract types `Affinity` policy, `AntiAffinity` policy 
so that an abstract AntiAffinity policy defined in the topology template would match against the concrete OpenStackAntiAffinity policy and not against the  OpenStackAffinity policy if this policy is defined on the location.

**Comment by stebenoist** [comment]
Yes, I agree it should be more understandable for users. What you think @loicalbertin  ?

**Comment by stebenoist** [comment]
Done !

**Comment by laurentganne** [comment]
Seeing this null pointer exception when attempting to select the location in the deployment wizard:
```
java.lang.NullPointerException: null
	at alien4cloud.tosca.context.ToscaContext$Context.addDependency(ToscaContext.java:161) ~[alien4cloud-tosca-2.1.1.jar!/:?]
	at alien4cloud.tosca.context.ToscaContext$Context.resetDependencies(ToscaContext.java:141) ~[alien4cloud-tosca-2.1.1.jar!/:?]
	at org.alien4cloud.alm.deployment.configuration.flow.modifiers.matching.PolicyMatchingReplaceModifier.init(PolicyMatchingReplaceModifier.java:46) ~[alien4cloud-core-2.1.1.jar!/:?]
	at org.alien4cloud.alm.deployment.configuration.flow.modifiers.matching.AbstractMatchingReplaceModifier.process(AbstractMatchingReplaceModifier.java:53) ~[alien4cloud-core-2.1.1.jar!/:?]
	at org.alien4cloud.alm.deployment.configuration.flow.modifiers.matching.PolicyMatchingReplaceModifier.process(PolicyMatchingReplaceModifier.java:56) ~[alien4cloud-core-2.1.1.jar!/:?]
	at org.alien4cloud.alm.deployment.configuration.flow.modifiers.matching.AbstractComposedModifier.lambda$process$0(AbstractComposedModifier.java:28) ~[alien4cloud-core-2.1.1.jar!/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_131]
	at org.alien4cloud.alm.deployment.configuration.flow.modifiers.matching.AbstractComposedModifier.process(AbstractComposedModifier.java:28) ~[alien4cloud-core-2.1.1.jar!/:?]
	at org.alien4cloud.alm.deployment.configuration.flow.FlowExecutor.execute(FlowExecutor.java:220) ~[alien4cloud-core-2.1.1.jar!/:?]
	at org.alien4cloud.alm.deployment.configuration.flow.FlowExecutor.executeDeploymentFlow(FlowExecutor.java:208) ~[alien4cloud-core-2.1.1.jar!/:?]

```
Also the server group modifier is not enabled by default.

**Comment by stebenoist** [comment]
The plugin is bound to the modifier with metadata a4c_policy_impl. Not sure we need to enable it explicitly.

**Comment by laurentganne** [comment]
> 
> 
> Seeing this null pointer exception when selecting the location in the deployment wizard:
> 
> ```
> java.lang.NullPointerException: null
> 	at alien4cloud.tosca.context.ToscaContext$Context.addDependency(ToscaContext.java:161) ~[alien4cloud-tosca-2.1.1.jar!/:?]
> 	at alien4cloud.tosca.context.ToscaContext$Context.resetDependencies(ToscaContext.java:141) ~[alien4cloud-tosca-2.1.1.jar!/:?]
> 	at org.alien4cloud.alm.deployment.configuration.flow.modifiers.matching.PolicyMatchingReplaceModifier.init(PolicyMatchingReplaceModifier.java:46) ~[alien4cloud-core-2.1.1.jar!/:?]
> 	at org.alien4cloud.alm.deployment.configuration.flow.modifiers.matching.AbstractMatchingReplaceModifier.process(AbstractMatchingReplaceModifier.java:53) ~[alien4cloud-core-2.1.1.jar!/:?]
> 	at org.alien4cloud.alm.deployment.configuration.flow.modifiers.matching.PolicyMatchingReplaceModifier.process(PolicyMatchingReplaceModifier.java:56) ~[alien4cloud-core-2.1.1.jar!/:?]
> 	at org.alien4cloud.alm.deployment.configuration.flow.modifiers.matching.AbstractComposedModifier.lambda$process$0(AbstractComposedModifier.java:28) ~[alien4cloud-core-2.1.1.jar!/:?]
> 	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_131]
> 	at org.alien4cloud.alm.deployment.configuration.flow.modifiers.matching.AbstractComposedModifier.process(AbstractComposedModifier.java:28) ~[alien4cloud-core-2.1.1.jar!/:?]
> 	at org.alien4cloud.alm.deployment.configuration.flow.FlowExecutor.execute(FlowExecutor.java:220) ~[alien4cloud-core-2.1.1.jar!/:?]
> 	at org.alien4cloud.alm.deployment.configuration.flow.FlowExecutor.executeDeploymentFlow(FlowExecutor.java:208) ~[alien4cloud-core-2.1.1.jar!/:?]
> ```
> 

The null pointer exception happened on a setup installed using yorc bootstrap.
It should be caused by a version change in the openstack types on the A4C plugin which is not reported on yorc bootstrap files.
In file https://github.com/ystia/yorc/blob/features/gh-84-openstack-anti-affinity-policy/commands/bootstrap/resources/topology/ondemand_resources_openstack.tmpl
versions 1.0.0 should be replaced by 1.1.0

**Comment by laurentganne** [comment]
Seeing an issue with the scale out operation :
although the operation finishes succesfully on Yorc, there is an issue on Alien4Cloud side: the deleted compute instance switches to deleting status, but will end up in status Initial.
So it still appears in the runtime view, as if an operation was still in progress.

**Pull request merged**
